use_frameworks!

platform :ios, '10.0'

target 'XYZKit_Example' do


  pod 'XYZKit', :path => '../'
  pod 'XYZKit/XYZEmptyBoard', :path => '../'
  pod 'XYZKit/XYZFloatDragView', :path => '../'
  pod 'XYZKit/XYZSMSCodeInputView', :path => '../'
  pod 'XYZKit/XYZBadgeView', :path => '../'
  pod 'XYZKit/XYZLinkView', :path => '../'
  pod 'XYZKit/XYZGuideView', :path => '../'



  target 'XYZKit_Tests' do
    inherit! :search_paths
  end
end
